### ISSUE TITLE
"Not on default branch -- aborting."

### ISSUE THREAD

**Issue by NBprojekt** [dtinth/todo-actions#51]
When I run this action everything seems to work, but no issues are created.

The logs
``` console
...
"Total TODOs found: 1"
"TODOs without references: 1"
"Not on default branch -- aborting."
```

Is seems to work to this point but it aborts because it is not an the "default branch".
The strange thing is that currently I only have 1 branch.

Did I forgot something in the config or is it a bug?

My action
```` yml
todo:
   name: Convet TODO comments to issues
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v1
    - uses: dtinth/todo-actions@v0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL: ${{ secrets.XACT_TODO_URL }}
```
